services:
  whatsapp-bridge:
    build:
      context: ./whatsapp-bridge
      dockerfile: Dockerfile
    container_name: whatsapp-bridge
    ports:
      - "8080:8080"
    volumes:
      - ./whatsapp-bridge/store:/app/store
      - ./whatsapp-bridge/session:/app/session
    environment:
      - CGO_ENABLED=1
      - HISTORY_DAYS_LIMIT=${HISTORY_DAYS_LIMIT:-30}
    restart: unless-stopped
    networks:
      - whatsapp-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  whatsapp-mcp-server:
    build:
      context: ./whatsapp-mcp-server
      dockerfile: Dockerfile
    container_name: whatsapp-mcp-server
    ports:
      - "18081:18081"
    volumes:
      - ./whatsapp-bridge/store:/app/store:ro
      - ./whatsapp-mcp-server/media:/app/media
    environment:
      - WHATSAPP_API_BASE_URL=http://whatsapp-bridge:8080/api
      - MESSAGES_DB_PATH=/app/store/messages.db
      - PYTHONUNBUFFERED=1
    depends_on:
      whatsapp-bridge:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - whatsapp-network

networks:
  whatsapp-network:
    driver: bridge

volumes:
  whatsapp_store:
  whatsapp_session:
  whatsapp_media:
